[package]
name = "bdk-cli"
version = "0.1.1-dev"
edition = "2018"
authors = ["Alekos Filini <alekos.filini@gmail.com>", "Riccardo Casatta <riccardo@casatta.it>", "Steve Myers <steve@notmandatory.org>"]
homepage = "https://bitcoindevkit.org"
repository = "https://github.com/bitcoindevkit/bdk-cli"
documentation = "https://docs.rs/bdk-cli"
description = "A CLI library and example CLI tool based on the BDK descriptor-based wallet library"
keywords = ["bitcoin", "wallet", "descriptor", "psbt"]
readme = "README.md"
license = "MIT"

[dependencies]
bdk = "^0.2"
bdk-macros = "^0.2"
structopt = "^0.3"
serde_json = { version = "^1.0" }
log = "^0.4"
base64 = "^0.11"

# Optional dependencies
async-trait = { version = "0.1", optional = true }
rustyline = { version = "6.0", optional = true }
dirs-next = { version = "2.0", optional = true }
env_logger = { version = "0.7", optional = true }
clap = { version = "2.33", optional = true }
tiny-bip39 = { version = "0.8", optional = true }

[features]
default = ["repl", "esplora"]
repl = ["async-trait", "rustyline", "dirs-next", "env_logger", "clap", "electrum"]
bip39 = ["bdk/keys-bip39", "tiny-bip39"]
electrum = ["bdk/electrum"]
esplora = ["bdk/esplora"]

[[bin]]
name = "bdk-cli"
path = "src/bdk_cli.rs"
required-features = ["repl"]

[[bin]]
name = "bip39-tool"
path = "src/bip39_tool.rs"
required-features = ["bip39"]
